package:
  name: needle

source:
  git_tag: 0.1
  git_url: https://github.com/danielballan/needle.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.7
    - scipy
    - pandas
    - scikit-image
    - matplotlib

test:
  imports:
    - needle

about:
  home: http://github.com/danielballan/needle
  license: 3-clause BSD3-clause BSD
